{
 "title": "Pods",
 "tags": [ "upguard-custom" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "controller",
    "label": "Controllers",
    "query": "label_values(kube_replicaset:kube_metadata_generation{namespace=~\"$namespace\"}, replicaset)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_owner{namespace=~\"$namespace\", pod=~\"^($controller)-[a-zA-Z]*[0-9][a-zA-Z0-9-]*$\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=\"$pod\", container=~\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "limits {{container}}"
    },
    {
     "expr": "sum by (container, pod, namespace)(rate(container_cpu_usage_seconds_total{container!=\"POD\", container=~\"$container\",pod=~\"$pod\", namespace=~\"$namespace\"}[5m])) ",
     "legendFormat": "current {{container}}, {{pod}}, {{namespace}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=\"$pod\", container=~\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "requests {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage (matches 'kubectl top pod')",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\", container=~\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "Limits: {{container}}"
    },
    {
     "expr": "sum by(container, pod, namespace) (container_memory_working_set_bytes{container!=\"POD\", container=~\"$container\",pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "Current: {{container}}, {{pod}}, {{namespace}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\", container=~\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "Requested: {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage from 'docker stats' + Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container, pod, namespace) (container_memory_usage_bytes{container!=\"POD\", container=~\"$container\",pod=~\"$pod\", namespace=~\"$namespace\"} - container_memory_cache{container!=\"POD\", container=~\"$container\",pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "Not Cache : {{container}}, {{pod}}, {{namespace}}"
    },
    {
     "expr": "sum by(container, pod, namespace) (container_memory_cache{container!=\"POD\", container=~\"$container\",pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "Cache: {{container}}, {{pod}}, {{namespace}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Rate over time interval",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod, namespace) (rate (container_network_receive_bytes_total{pod=~\"$pod\", namespace=~\"$namespace\"}[1m]) ))*8",
     "legendFormat": "received: {{pod}} {{namespace}}"
    },
    {
     "expr": "sort_desc(sum by (pod, namespace) (rate (container_network_transmit_bytes_total{pod=~\"$pod\", namespace=~\"$namespace\"}[1m]) ))*8",
     "legendFormat": "transmitted: {{pod}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Disk I/O - Attached disks only (see k8s repo under /gke/prometheus/upguard/grafana-dashboards/pods.jsonnet for more info)",
   "type": "graph",
   "description": "Uses node-level Disk I/O stats (due to inaccurate container-level Disk I/O stats from cAdvisor), only pods (secure-pg-0, golang-agent) with volume mounts will report accurate Disk I/O stats.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m]) + on(instance,device) group_left(namespace, pod, container) (sum:container_fs_info{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", device!~\"sda\"})",
     "legendFormat": "writes: {{namespace}} {{container}} {{pod}} /dev/{{device}}"
    },
    {
     "expr": "rate(node_disk_read_bytes_total[1m]) + on(instance,device) group_left(namespace, pod, container) (sum:container_fs_info{container=~\"$container\", pod=~\"$pod\", namespace=~\"$namespace\", device!~\"sda\"})",
     "legendFormat": "reads: {{namespace}} {{container}} {{pod}} /dev/{{device}}"
    }
   ]
  },
  {
   "title": "Total Restarts Per Container",
   "type": "graph",
   "description": "Containers with no restarts are hidden",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", container!=\"POD\", container=~\"$container\",pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} {{pod}} {{container}}"
    }
   ]
  }
 ]
}